version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: gostruct_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gostructdb        # Default DB to create
      MYSQL_USER: gostructuser          # User you want to create
      MYSQL_PASSWORD: gostructpass      # Password for above user
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
