# config.development.yaml - for structured config
env: development

server_port: 8080


cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
  allow_credentials: true

microsoft:
  client_id: "3b433f4a-a455-4189-bcd9-4830f175a69c"
  client_secret: "So28Q~w6VjG6x2TKYBvso58EK6KyDZ7IKPKSvcsI"
  tenant: "efda937d-84e0-40c4-9af3-7c13939e1814"  # or your tenant ID
  redirect_uri: "http://localhost:8080/v1/auth/microsoft/callback"

databases:
  db1:
    user: gostructuser
    password: gostructpass
    name: gostruct_default
    host: 127.0.0.1
    port: 3306
    migration: true

  db2:
    user: gostruct_rdb_user
    password: strongpassword
    name: gostruct_rdb
    host: 127.0.0.1
    port: 3306
    migration: true

  db3:
    user: gostruct_analytics_user
    password: analyticsPass
    name: gostruct_analytics
    host: 127.0.0.1
    port: 3306
    migration: true

